-- filix-shadowwork-api/Database/DDL.sql
-- Cloudflare Durable Objects SQLite / D1-compatible schema

-- NOTE:
-- This file is the canonical schema definition.
-- Runtime migrations may diverge; update this file intentionally.

PRAGMA foreign_keys = ON;

-- =========================
-- Runs (one program cycle per user; supports "やり直し")
-- =========================
CREATE TABLE IF NOT EXISTS runs (
    id      TEXT PRIMARY KEY,
    user_id TEXT NOT NULL,

    -- Human-friendly sequence number per user (1,2,3,...)
    run_no  INTEGER NOT NULL,

    status  TEXT NOT NULL DEFAULT 'active', -- 'active' | 'completed'

    created_at TEXT NOT NULL DEFAULT (DATETIME('now')),
    updated_at TEXT NOT NULL DEFAULT (DATETIME('now')),

    CHECK (status IN ('active', 'completed'))
);

-- One active run per user
CREATE UNIQUE INDEX IF NOT EXISTS idx_runs_user_active
    ON runs(user_id)
    WHERE status = 'active';

-- Unique run number per user
CREATE UNIQUE INDEX IF NOT EXISTS idx_runs_user_run_no
    ON runs(user_id, run_no);

-- Keep updated_at current (safe / non-recursive by guard)
DROP TRIGGER IF EXISTS trg_runs_updated_at;

CREATE TRIGGER IF NOT EXISTS trg_runs_updated_at
AFTER UPDATE ON runs
FOR EACH ROW
WHEN NEW.updated_at = OLD.updated_at
BEGIN
    UPDATE runs
        SET updated_at = DATETIME('now')
        WHERE id = NEW.id;
END;

-- =========================
-- Threads (1 page = 1 thread; either a Step1 question or a Step2 session topic)
-- =========================
CREATE TABLE IF NOT EXISTS threads (
    id      TEXT PRIMARY KEY,
    run_id  TEXT NOT NULL,
    user_id TEXT NOT NULL,

    step INTEGER NOT NULL, -- 1 or 2

    -- Step 1: question_no is used, session_no must be NULL (nullable by design)
    question_no INTEGER,

    -- Step 2: session_no is used, question_no must be NULL (nullable by design)
    session_no  INTEGER,

    status TEXT NOT NULL DEFAULT 'active', -- 'active' | 'completed'

    created_at TEXT NOT NULL DEFAULT (DATETIME('now')),
    updated_at TEXT NOT NULL DEFAULT (DATETIME('now')),

    FOREIGN KEY (run_id) REFERENCES runs(id) ON DELETE CASCADE,

    CHECK (step IN (1, 2)),
    CHECK (status IN ('active', 'completed')),
    CHECK (
        (step = 1 AND question_no IS NOT NULL AND session_no IS NULL) OR
        (step = 2 AND session_no IS NOT NULL AND question_no IS NULL)
    )
);

-- One active thread per run (the page currently writable)
CREATE UNIQUE INDEX IF NOT EXISTS idx_threads_run_active
    ON threads(run_id)
    WHERE status = 'active';

-- Uniqueness within a run
CREATE UNIQUE INDEX IF NOT EXISTS idx_threads_run_step_question
    ON threads(run_id, step, question_no)
    WHERE step = 1;

CREATE UNIQUE INDEX IF NOT EXISTS idx_threads_run_step_session
    ON threads(run_id, step, session_no)
    WHERE step = 2;

-- Common query patterns
CREATE INDEX IF NOT EXISTS idx_threads_user_created
    ON threads(user_id, created_at);

CREATE INDEX IF NOT EXISTS idx_threads_run_created
    ON threads(run_id, created_at);

-- Keep updated_at current (safe / non-recursive by guard)
DROP TRIGGER IF EXISTS trg_threads_updated_at;

CREATE TRIGGER IF NOT EXISTS trg_threads_updated_at
AFTER UPDATE ON threads
FOR EACH ROW
WHEN NEW.updated_at = OLD.updated_at
BEGIN
    UPDATE threads
        SET updated_at = DATETIME('now')
        WHERE id = NEW.id;
END;

-- =========================
-- Messages (conversation log within a thread)
-- =========================
CREATE TABLE IF NOT EXISTS messages (
    id TEXT PRIMARY KEY,

    run_id    TEXT NOT NULL,
    thread_id TEXT NOT NULL,
    user_id   TEXT NOT NULL,

    role TEXT NOT NULL, -- 'user' | 'assistant' (system can be added later)

    -- Idempotency key generated by client for retry-safe persistence
    client_message_id TEXT NOT NULL,

    -- Encrypted content only (never plaintext)
    content TEXT NOT NULL,
    content_iv TEXT NOT NULL,
    content_alg TEXT NOT NULL,
    content_v INTEGER NOT NULL DEFAULT 1,
    content_kid TEXT,

    -- Strict ordering within a thread (DO NOT rely on created_at for ordering)
    seq INTEGER NOT NULL,

    created_at TEXT NOT NULL DEFAULT (DATETIME('now')),

    FOREIGN KEY (run_id)    REFERENCES runs(id)    ON DELETE CASCADE,
    FOREIGN KEY (thread_id) REFERENCES threads(id) ON DELETE CASCADE,

    CHECK (role IN ('user', 'assistant'))
);

-- Ordering and retrieval
CREATE UNIQUE INDEX IF NOT EXISTS idx_messages_thread_seq
    ON messages(thread_id, seq);

CREATE UNIQUE INDEX IF NOT EXISTS idx_messages_thread_client_message_id
    ON messages(thread_id, client_message_id);

-- Common query patterns
CREATE INDEX IF NOT EXISTS idx_messages_user_created
    ON messages(user_id, created_at);

CREATE INDEX IF NOT EXISTS idx_messages_run_created
    ON messages(run_id, created_at);

CREATE INDEX IF NOT EXISTS idx_messages_thread_created
    ON messages(thread_id, created_at);

-- =========================
-- Cards (encrypted context cards)
-- =========================
CREATE TABLE IF NOT EXISTS cards (
    id TEXT PRIMARY KEY,

    run_id TEXT NOT NULL,
    thread_id TEXT,
    user_id TEXT NOT NULL,

    kind TEXT NOT NULL, -- 'context_card' | 'step2_meta_card'

    -- Encrypted content only (never plaintext)
    content TEXT NOT NULL,
    content_iv TEXT NOT NULL,
    content_alg TEXT NOT NULL,
    content_v INTEGER NOT NULL DEFAULT 1,
    content_kid TEXT,

    created_at TEXT NOT NULL DEFAULT (DATETIME('now')),
    updated_at TEXT NOT NULL DEFAULT (DATETIME('now')),

    FOREIGN KEY (run_id) REFERENCES runs(id) ON DELETE CASCADE,
    FOREIGN KEY (thread_id) REFERENCES threads(id) ON DELETE CASCADE,

    CHECK (kind IN ('context_card', 'step2_meta_card')),
    CHECK (
        (kind = 'context_card' AND thread_id IS NOT NULL) OR
        (kind = 'step2_meta_card' AND thread_id IS NULL)
    )
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_cards_thread_kind
    ON cards(thread_id, kind)
    WHERE kind = 'context_card';

CREATE UNIQUE INDEX IF NOT EXISTS idx_cards_run_kind
    ON cards(run_id, kind)
    WHERE kind = 'step2_meta_card';

CREATE INDEX IF NOT EXISTS idx_cards_user_created
    ON cards(user_id, created_at);

-- =========================
-- User-level flags (payment gate etc.)
-- =========================
CREATE TABLE IF NOT EXISTS user_flags (
    user_id TEXT PRIMARY KEY,
    paid INTEGER NOT NULL DEFAULT 0,

    created_at TEXT NOT NULL DEFAULT (DATETIME('now')),
    updated_at TEXT NOT NULL DEFAULT (DATETIME('now')),

    CHECK (paid IN (0, 1))
);

-- Keep updated_at current (safe / non-recursive by guard)
DROP TRIGGER IF EXISTS trg_user_flags_updated_at;

CREATE TRIGGER IF NOT EXISTS trg_user_flags_updated_at
AFTER UPDATE ON user_flags
FOR EACH ROW
WHEN NEW.updated_at = OLD.updated_at
BEGIN
    UPDATE user_flags
        SET updated_at = DATETIME('now')
        WHERE user_id = NEW.user_id;
END;

-- =========================
-- Stripe Webhook Events (idempotency)
-- =========================
CREATE TABLE IF NOT EXISTS stripe_webhook_events (
    event_id TEXT PRIMARY KEY,
    event_type TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT (DATETIME('now'))
);
